name: flutter_suction
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^3.1.0
  riverpod: ^3.0.0-dev.16
  flutter_riverpod: ^3.0.0-dev.16
  riverpod_annotation: ^3.0.0-dev.16

  http: ^1.2.2
  path: ^1.9.0
  path_provider: ^2.1.4
  universal_io: ^2.2.2
  flutter_secure_storage: ^9.2.2

  flutter_code_editor: ^0.3.2
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  share_plus: ^10.0.2

  go_router: ^14.2.3
  file_selector: ^1.0.3
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.0-dev.16
  build_runner: ^2.4.11
  freezed: ^3.1.0
  json_serializable: ^6.9.2

flutter:
  uses-material-design: true
